Rig313.Web/Areas/Shop/Models/CategoryViewModel.cs
using Rig313.Core.Categories;
using Rig313.Core.Inventories;
using Rig313.Core.Products;

namespace Rig313.Web.Areas.Shop.Models
{
	public class CategoryViewModel
	{
        public IEnumerable<Category?> Categories { get; set; }
        public IEnumerable<Product?> Products { get; set; }
        public Category Category { get; set; }
    }
}

Rig313.Web/Areas/Shop/Models/HomeViewModel.cs
using Rig313.Core.Categories;
using Rig313.Core.Products;

namespace Rig313.Web.Areas.Shop.Models
{
	public class HomeViewModel
	{
        public IEnumerable<Category?> Categories { get; set; }
        public IEnumerable<Product?> NewProducts { get; set; }
    }
}

Rig313.Web/Areas/Shop/Models/ProductViewModel.cs
using Rig313.Core.Categories;
using Rig313.Core.Inventories;
using Rig313.Core.Products;

namespace Rig313.Web.Areas.Shop.Models
{
	public class ProductViewModel
	{
        public IEnumerable<Category?> Categories { get; set; }
		public Product Product { get; set; }
		public Inventory Inventory { get; set; }
		public Category Category { get; set; }
    }
}

Rig313.Web/Models/ErrorViewModel.cs
namespace Rig313.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Rig313.Web/Areas/Shop/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using Rig313.Web.Models;
using System.Diagnostics;

namespace Rig313.Web.Areas.Shop.Controllers
{
    [Area("Shop")]
    public class CartController : Controller
    {
        private readonly ILogger<CartController> _logger;

        public CartController(ILogger<CartController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Checkout()
        {
            return View();
        }


        

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Rig313.Web/Areas/Shop/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Rig313.Core.Categories;
using Rig313.Core.Customers;
using Rig313.Core.Products;
using Rig313.Data.IRepository;
using Rig313.Services;
using Rig313.Web.Areas.Shop.Models;
using Rig313.Web.Models;
using System.Diagnostics;

namespace Rig313.Web.Areas.Shop.Controllers
{
    [Area("Shop")]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly CategoryService _categoryService;
        private readonly ProductService _productService;

        public HomeController(ILogger<HomeController> logger, CategoryService categoryService, ProductService productService)
        {
            _logger = logger;
            _categoryService = categoryService;
            _productService = productService;
        }

        public IActionResult Index()
        {
            HomeViewModel model = new HomeViewModel();
            model.Categories = _categoryService.GetAllCategories();
            model.NewProducts = _productService.GetNewFiveProducts();
			return View(model);
        }

        public IActionResult Profile()
        {
            return View();
        }

		public IActionResult Registration()
		{
			return View();
		}
        
		public IActionResult Login()
		{
			return View();
		}

		public IActionResult Privacy()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Rig313.Web/Areas/Shop/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Rig313.Web.Models;
using System.Diagnostics;

namespace Rig313.Web.Areas.Shop.Controllers
{
    [Area("Shop")]
    public class OrderController : Controller
    {
        private readonly ILogger<OrderController> _logger;

        public OrderController(ILogger<OrderController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
		public IActionResult Details(int? id)
		{
			return View();
		}



		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Rig313.Web/Areas/Shop/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Rig313.Services;
using Rig313.Web.Areas.Shop.Models;
using Rig313.Web.Models;
using System.Diagnostics;

namespace Rig313.Web.Areas.Shop.Controllers
{
    [Area("Shop")]
    public class ProductController : Controller
    {
        private readonly ILogger<ProductController> _logger;
        private readonly CategoryService _categoryService;
        private readonly ProductService _productService;
        private readonly InventoryService _inventoryService;


		public ProductController(ILogger<ProductController> logger, CategoryService categoryService,
            ProductService productService, InventoryService inventoryService)
		{
			_logger = logger;
            _categoryService = categoryService;
            _productService = productService;
            _inventoryService = inventoryService;
		}

		public IActionResult Index()
        {
            return RedirectToAction("Index", "Home");
        }

        public IActionResult Details(int? id)
        {
			if (id == null) return NotFound();
			ProductViewModel model = new ProductViewModel();
			model.Categories = _categoryService.GetAllCategories();
			model.Product = _productService.GetProductById((int)id);
			model.Inventory = _inventoryService.GetInventoryByProductId((int)id);
			model.Category = _categoryService.GetById((int)model.Product.CategoryId);
			return View(model);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Rig313.Web/Areas/Shop/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using Rig313.Core.Categories;
using Rig313.Core.Products;
using Rig313.Data.IRepository;
using Rig313.Services;
using Rig313.Web.Areas.Shop.Models;
using Rig313.Web.Models;
using System.Diagnostics;

namespace Rig313.Web.Areas.Shop.Controllers
{
    [Area("Shop")]
    public class ProductsController : Controller
    {
        private readonly ILogger<ProductsController> _logger;
		private readonly CategoryService _categoryService;
		private readonly ProductService _productService;

		public ProductsController(ILogger<ProductsController> logger, CategoryService categoryService, ProductService productService)
        {
            _logger = logger;
            _categoryService = categoryService;
            _productService = productService;
        }

        public IActionResult Index()
        {
            return RedirectToAction("Index", "Home");
        }

        public IActionResult Category(int? id)
        {
            if (id == null) return NotFound();
            if (id == 0) return NotFound();
            if (id.GetType() != typeof(int)) return NotFound();
			
			CategoryViewModel categoryViewModel = new CategoryViewModel();

            categoryViewModel.Categories = _categoryService.GetAllCategories();
            categoryViewModel.Category = _categoryService.GetById((int)id);
			if (categoryViewModel.Category == null) return NotFound();
			categoryViewModel.Products = _productService.GetAllProducts().Where(u => u.CategoryId == id).ToList();
            return View(categoryViewModel);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Rig313.Web/Areas/Shop/Views/Cart/Checkout.cshtml
@{
	ViewData["Title"] = "Checkout";
}
<div class="section">
	<!-- container -->
	<div class="container">
		<div class="product">
			<div class="row container-fluid flex-lg-row" style="padding-top:15px; margin-bottom:-15px;">
				<div class="product-img col-md-1">
					<img src="~/img/product01.png" alt="">
				</div>
				<div class="product-body col-md-4" style="vertical-align:middle;">
					<h3 class="product-name" style="font-size:125%;"><a asp-area="Shop" asp-controller="Product" asp-action="Details" asp-route-id="productid">product name goes here</a></h3>
				</div>
				<div class="product-body col-md-3 m-auto">
					<h5 class="product-price d-inline-block">Unit Price: $980.00 <del class="product-old-price">$1000.00</del></h5>
					<h5 class="product-price d-inline-block">Quantity : x1</h5>
				</div>
				<div class="product-body col-md-3" style="vertical-align:middle; text-align:right;">
					<h3 class="" style="font-size:125%;">Price : $980.00</h3>
				</div>
				<div class="product-body col-md-1" style="vertical-align:middle;">
					<button class="btn btn-danger"><i class="fa fa-trash"></i></button>
				</div>
			</div>
			<hr/>
			<div class="row container-fluid flex-lg-row" style="padding-top:15px; margin-bottom:-15px;">
				<div class="product-img col-md-1">
					<img src="~/img/product01.png" alt="">
				</div>
				<div class="product-body col-md-4" style="vertical-align:middle;">
					<h3 class="product-name" style="font-size:125%;"><a asp-area="Shop" asp-controller="Product" asp-action="Details" asp-route-id="productid">product name goes here</a></h3>
				</div>
				<div class="product-body col-md-3 m-auto">
					<h5 class="product-price d-inline-block">Unit Price: $980.00 <del class="product-old-price">$1000.00</del></h5>
					<h5 class="product-price d-inline-block">Quantity : x1</h5>
				</div>
				<div class="product-body col-md-3" style="vertical-align:middle; text-align:right;">
					<h3 class="" style="font-size:125%;">Price : $980.00</h3>
				</div>
				<div class="product-body col-md-1" style="vertical-align:middle;">
					<button class="btn btn-danger"><i class="fa fa-trash"></i></button>
				</div>
			</div>
			<hr/>
			<div class="row container-fluid flex-lg-row">
				<div class="col-md-1">
					
				</div>
				<div class="col-md-4" style="vertical-align:middle;">
					
				</div>
				<div class="col-md-6" style="vertical-align:middle; text-align:right;">
					<h3 class="" style="font-size:125%;">Subtotal : $1960.00</h3>
					<h3 class="" style="font-size:125%;">Shipment Charge : $2.00</h3>
					<h3 class="" style="font-size:125%;">Total : $1962.00</h3>
					<br/>
				</div>
				<div class="col-md-1" style="vertical-align:middle;">
				</div>

			</div>
			<hr/>
			<form method="post" class="form-check" style="width:90%; margin:auto">
				<div class="form-group">
					<h4>Receiver's Name</h4>
					<input type="text" class="form-control" cols="100" name="receiversname" value="Receiver's Name Here" disabled required>
				</div>
                <div class="form-group">
                    <h4>Contact Number</h4>
					<input type="text" class="form-control" cols="100" name="phone" value="Contact Number Here" disabled required>
                </div>
				<div class="form-group">
					<h4>Shipping Address</h4>
					<textarea rows="6" class="form-control" name="address"></textarea>
				</div>
				
				<a asp-area="Shop" asp-controller="Cart" asp-action="Index" class="btn btn-primary"><i class="fa fa-arrow-left"></i> Go Back</a>
				<button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Place Order</button>
			</form>
				
			<br />
		</div>

	</div>
	<!-- /container -->
</div>
<!-- /SECTION -->
<br />
<br />
<br />

Rig313.Web/Areas/Shop/Views/Cart/Index.cshtml
@{
	ViewData["Title"] = "Your Cart";
}
<div class="section">
	<!-- container -->
	<div class="container">
		<div class="product">
			<div class="row container-fluid flex-lg-row" style="padding-top:15px; margin-bottom:-15px;">
				<div class="product-img col-md-1">
					<img src="~/img/product01.png" alt="">
				</div>
				<div class="product-body col-md-4" style="vertical-align:middle;">
					<h3 class="product-name" style="font-size:125%;"><a asp-area="Shop" asp-controller="Product" asp-action="Details" asp-route-id="productid">product name goes here</a></h3>
				</div>
				<div class="product-body col-md-3 m-auto">
					<h5 class="product-price d-inline-block">Unit Price: $980.00 <del class="product-old-price">$1000.00</del></h5>
					<h5 class="product-price d-inline-block">Quantity : x1</h5>
				</div>
				<div class="product-body col-md-3" style="vertical-align:middle; text-align:right;">
					<h3 class="" style="font-size:125%;">Price : $980.00</h3>
				</div>
				<div class="product-body col-md-1" style="vertical-align:middle;">
					<button class="btn btn-danger"><i class="fa fa-trash"></i></button>
				</div>
			</div>
			<hr/>
			<div class="row container-fluid flex-lg-row" style="padding-top:15px; margin-bottom:-15px;">
				<div class="product-img col-md-1">
					<img src="~/img/product01.png" alt="">
				</div>
				<div class="product-body col-md-4" style="vertical-align:middle;">
					<h3 class="product-name" style="font-size:125%;"><a asp-area="Shop" asp-controller="Product" asp-action="Details" asp-route-id="productid">product name goes here</a></h3>
				</div>
				<div class="product-body col-md-3 m-auto">
					<h5 class="product-price d-inline-block">Unit Price: $980.00 <del class="product-old-price">$1000.00</del></h5>
					<h5 class="product-price d-inline-block">Quantity : x1</h5>
				</div>
				<div class="product-body col-md-3" style="vertical-align:middle; text-align:right;">
					<h3 class="" style="font-size:125%;">Price : $980.00</h3>
				</div>
				<div class="product-body col-md-1" style="vertical-align:middle;">
					<button class="btn btn-danger"><i class="fa fa-trash"></i></button>
				</div>
			</div>
			<hr/>
			<div class="row container-fluid flex-lg-row">
				<div class="col-md-1">
					
				</div>
				<div class="col-md-4" style="vertical-align:middle;">
					
				</div>
				<div class="col-md-6" style="vertical-align:middle; text-align:right;">
					<h3 class="" style="font-size:125%;">Subtotal : $1960.00</h3>
					<h3 class="" style="font-size:125%;">Shipment Charge : $2.00</h3>
					<h3 class="" style="font-size:125%;">Total : $1962.00</h3>
					<br/>
					<a asp-area="Shop" asp-controller="Home" asp-action="Index" class="btn btn-primary"><i class="fa fa-shopping-bag"></i> Continue Shopping</a>
					<a asp-area="Shop" asp-controller="Cart" asp-action="Checkout" class="btn btn-success"><i class="fa fa-check"></i> Checkout</a>
				</div>
				<div class="col-md-1" style="vertical-align:middle;">
				</div>

			</div>
			<hr/>

		</div>

	</div>
	<!-- /container -->
</div>
<!-- /SECTION -->
<br />
<br />
<br />

Rig313.Web/Areas/Shop/Views/Order/Details.cshtml
@{
	ViewData["Title"] = "Checkout";
}
<div class="section">
	<!-- container -->
	<div class="container">
		<div class="product">
			<div class="row container-fluid flex-lg-row" style="padding-top:15px; margin-bottom:-15px;">
				<div class="product-img col-md-1">
					<img src="~/img/product01.png" alt="">
				</div>
				<div class="product-body col-md-4" style="vertical-align:middle;">
					<h3 class="product-name" style="font-size:125%;"><a asp-area="Shop" asp-controller="Product" asp-action="Details" asp-route-id="productid">product name goes here</a></h3>
				</div>
				<div class="product-body col-md-3 m-auto">
					<h5 class="product-price d-inline-block">Unit Price: $980.00 <del class="product-old-price">$1000.00</del></h5>
					<h5 class="product-price d-inline-block">Quantity : x1</h5>
				</div>
				<div class="product-body col-md-3" style="vertical-align:middle; text-align:right;">
					<h3 class="" style="font-size:125%;">Price : $980.00</h3>
				</div>
				<div class="product-body col-md-1" style="vertical-align:middle;">
					
				</div>
			</div>
			<hr />
			<div class="row container-fluid flex-lg-row" style="padding-top:15px; margin-bottom:-15px;">
				<div class="product-img col-md-1">
					<img src="~/img/product01.png" alt="">
				</div>
				<div class="product-body col-md-4" style="vertical-align:middle;">
					<h3 class="product-name" style="font-size:125%;"><a asp-area="Shop" asp-controller="Product" asp-action="Details" asp-route-id="productid">product name goes here</a></h3>
				</div>
				<div class="product-body col-md-3 m-auto">
					<h5 class="product-price d-inline-block">Unit Price: $980.00 <del class="product-old-price">$1000.00</del></h5>
					<h5 class="product-price d-inline-block">Quantity : x1</h5>
				</div>
				<div class="product-body col-md-3" style="vertical-align:middle; text-align:right;">
					<h3 class="" style="font-size:125%;">Price : $980.00</h3>
				</div>
				<div class="product-body col-md-1" style="vertical-align:middle;">
					
				</div>
			</div>
			<hr />
			<div class="row container-fluid flex-lg-row">
				<div class="col-md-1">
				</div>
				<div class="col-md-4" style="vertical-align:middle;">
				</div>
				<div class="col-md-6" style="vertical-align:middle; text-align:right;">
					<h3 class="" style="font-size:125%;">Subtotal : $1960.00</h3>
					<h3 class="" style="font-size:125%;">Shipment Charge : $2.00</h3>
					<h3 class="" style="font-size:125%;">Total : $1962.00</h3>
					<br />
				</div>
				<div class="col-md-1" style="vertical-align:middle;">
				</div>

			</div>
			<div class="row container-fluid flex-lg-row">
				<div class="col-md-1">
				</div>
				<div class="col-md-4" style="vertical-align:middle;">
				</div>
				<div class="col-md-6" style="vertical-align:middle; text-align:right;">
					<h3 class="" style="font-size:125%;">Status : Pending</h3>
					<br />
				</div>
				<div class="col-md-1" style="vertical-align:middle;">
				</div>

			</div>
			<hr />
			<form method="post" class="form-check" style="width:90%; margin:auto">
				<div class="form-group">
					<h4>Receiver's Name</h4>
					<input type="text" class="form-control" cols="100" name="receiversname" value="Receiver's Name Here" disabled required>
				</div>
				<div class="form-group">
					<h4>Contact Number</h4>
					<input type="text" class="form-control" cols="100" name="phone" value="Contact Number Here" disabled required>
				</div>
				<div class="form-group">
					<h4>Shipping Address</h4>
					<textarea rows="6" class="form-control" name="address" disabled></textarea>
				</div>

				<a asp-area="Shop" asp-controller="Order" asp-action="Index" class="btn btn-primary"><i class="fa fa-arrow-left"></i> Go Back</a>
			</form>

			<br />
		</div>

	</div>
	<!-- /container -->
</div>
<!-- /SECTION -->
<br />
<br />
<br />

Rig313.Web/Views/Shared/_Layout.cshtml
@{
	
}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>@ViewData["Title"] - Rig313</title>
	<link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700" rel="stylesheet">
	<link type="text/css" rel="stylesheet" href="~/css/bootstrap.min.css" />
	<link type="text/css" rel="stylesheet" href="~/css/slick.css" />
	<link type="text/css" rel="stylesheet" href="~/css/slick-theme.css" />
	<link type="text/css" rel="stylesheet" href="~/css/nouislider.min.css" />
	<link rel="stylesheet" href="~/css/font-awesome.min.css">
	<link type="text/css" rel="stylesheet" href="~/css/style.css" />

</head>
<body>
	<header>
		<div id="top-header">
			<div class="container">
				<ul class="header-links pull-left">
					<li><a href="#"><i class="fa fa-phone"></i> +880123456789</a></li>
					<li><a href="#"><i class="fa fa-envelope-o"></i> rig313@example.com</a></li>
					<li><a href="#"><i class="fa fa-map-marker"></i> DUET Area, Gazipur</a></li>
				</ul>
				<ul class="header-links pull-right">
					<li><a href="#"><i class="fa fa-dollar"></i> BDT</a></li>
					<li><a asp-area="Shop" asp-controller="Home" asp-action="Profile"><i class="fa fa-user-o"></i> My Account</a></li>
					<li>
						<a asp-area="Shop" asp-controller="Home" asp-action="Registration"><i class="fa fa-user-o"></i> Registration</a> <a>/</a> 
						<a asp-area="Shop" asp-controller="Home" asp-action="Login">Login</a>
					</li>
					<li><a asp-area="Shop" asp-controller="Order" asp-action="Index"><i class="fa fa-shopping-bag"></i> Orders</a></li>
				</ul>
			</div>
		</div>
		
		<div id="header">
			<div class="container">
				<div class="row">
					<div class="col-md-3">
						<div class="header-logo">
							<a asp-area="Shop" asp-controller="Home" asp-action="Index" class="logo">
								<img src="~/img/logo.png" alt="">
							</a>
						</div>
					</div>

					<div class="col-md-6">
						<div class="header-search">
							<form>
								<input class="input input-select" placeholder="Search here">
								<button class="search-btn">Search</button>
							</form>
						</div>
					</div>
					<div class="col-md-3 clearfix">
						<div class="header-ctn" style="cursor:pointer;">
							
							<div class="dropdown">
								<a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
									<i class="fa fa-shopping-cart"></i>
									<span>Your Cart</span>
									<div class="qty">3</div>
								</a>
								<div class="cart-dropdown">
									<div class="cart-list">
										<div class="product-widget">
											<div class="product-img">
												<img src="~/img/product01.png" alt="">
											</div>
											<div class="product-body">
												<h3 class="product-name"><a href="#">product name goes here</a></h3>
												<h4 class="product-price"><span class="qty">1x</span>$980.00</h4>
											</div>
											<button class="delete"><i class="fa fa-close"></i></button>
										</div>

										<div class="product-widget">
											<div class="product-img">
												<img src="~/img/product02.png" alt="">
											</div>
											<div class="product-body">
												<h3 class="product-name"><a href="#">product name goes here</a></h3>
												<h4 class="product-price"><span class="qty">3x</span>$980.00</h4>
											</div>
											<button class="delete"><i class="fa fa-close"></i></button>
										</div>
									</div>
									<div class="cart-summary">
										<small>3 Item(s) selected</small>
										<h5>SUBTOTAL: $2940.00</h5>
									</div>
									<div class="cart-btns">
										<a asp-area="Shop" asp-controller="Cart" asp-action="Index">View Cart</a>
										<a asp-area="Shop" asp-controller="Cart" asp-action="Checkout">Checkout  <i class="fa fa-arrow-circle-right"></i></a>
									</div>
								</div>
							</div>
							<div class="menu-toggle">
								<a href="#">
									<i class="fa fa-bars"></i>
									<span>Menu</span>
								</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</header>

	<!-- /NAVIGATION -->
	<!-- SECTION -->



	<main role="main" class="pb-3">
		@RenderBody()
	</main>
	


	<!-- FOOTER -->
	<footer id="footer">
		<!-- top footer -->
		<div class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<div class="col-md-3 col-xs-6">
						<div class="footer">
							<h3 class="footer-title">About Us</h3>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut.</p>
							<ul class="footer-links">
								<li><a href="#"><i class="fa fa-map-marker"></i>DUET Area, Gazipur</a></li>
								<li><a href="#"><i class="fa fa-phone"></i>+880123456789</a></li>
								<li><a href="#"><i class="fa fa-envelope-o"></i>rig313@example.com</a></li>
							</ul>
						</div>
					</div>

					<div class="col-md-3 col-xs-6">
						<div class="footer">
							
						</div>
					</div>

					<div class="clearfix visible-xs"></div>

					<div class="col-md-3 col-xs-6">
						<div class="footer">
							<h3 class="footer-title">Information</h3>
							<ul class="footer-links">
								<li><a href="#">Contact Us</a></li>
								<li><a href="#">Privacy Policy</a></li>
								<li><a href="#">Orders and Returns</a></li>
								<li><a href="#">Terms & Conditions</a></li>
							</ul>
						</div>
					</div>

					<div class="col-md-3 col-xs-6">
						<div class="footer">
							<h3 class="footer-title">Service</h3>
							<ul class="footer-links">
								<li><a href="#">My Account</a></li>
								<li><a href="#">View Cart</a></li>
								<li><a href="#">Track My Order</a></li>
								<li><a href="#">Help</a></li>
							</ul>
						</div>
					</div>
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /top footer -->
		<!-- bottom footer -->
		<div id="bottom-footer" class="section">
			<div class="container">
				<!-- row -->
				<div class="row">
					<div class="col-md-12 text-center">
						<ul class="footer-payments">
							<li><a href="#"><i class="fa fa-cc-visa"></i></a></li>
							<li><a href="#"><i class="fa fa-credit-card"></i></a></li>
							<li><a href="#"><i class="fa fa-cc-paypal"></i></a></li>
							<li><a href="#"><i class="fa fa-cc-mastercard"></i></a></li>
							<li><a href="#"><i class="fa fa-cc-discover"></i></a></li>
							<li><a href="#"><i class="fa fa-cc-amex"></i></a></li>
						</ul>
						<span class="copyright">
							<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
							Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
							<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						</span>
					</div>
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /bottom footer -->
	</footer>
	<!-- /FOOTER -->
	<!-- jQuery Plugins -->
	<script src="~/js/jquery.min.js"></script>
	<script src="~/js/bootstrap.min.js"></script>
	<script src="~/js/slick.min.js"></script>
	<script src="~/js/nouislider.min.js"></script>
	<script src="~/js/jquery.zoom.min.js"></script>
	<script src="~/js/main.js"></script>

</body>
</html>

Rig313.Web/Views/Shared/_NavigationPartial.cshtml
<nav id="navigation">
	<!-- container -->
	<div class="container">
		<!-- responsive-nav -->
		<div id="responsive-nav">
			<!-- NAV -->
			<ul class="main-nav nav navbar-nav flex-grow-1">
				<li class="active"><a asp-area="Shop" asp-controller="Home" asp-action="Index">Home</a></li>

				@foreach (var item in Model.Categories)
				{
					<li><a asp-area="Shop" asp-controller="Products" asp-action="Category" asp-route-id="@item.Id">@item.Name</a></li>
				}
			</ul>
			<!-- /NAV -->
		</div>
		<!-- /responsive-nav -->
	</div>
	<!-- /container -->
</nav>